export const TlPlConst = {
    GET_TRIAL_BALANCE_REQUEST: 'GET_TRIAL_BALANCE_REQUEST',
    GET_TRIAL_BALANCE_RESPONSE: 'GET_TRIAL_BALANCE_RESPONSE',

    GET_FLAT_ACCOUNT_W_GROUP_REQUEST: 'GET_FLAT_ACCOUNT_W_GROUP_REQUEST',
    GET_FLAT_ACCOUNT_W_GROUP_RESPONSE: 'GET_FLAT_ACCOUNT_W_GROUP_RESPONSE'
};
