export const TlPlConst = {
    GET_TRIAL_BALANCE_REQUEST: 'GET_TRIAL_BALANCE_REQUEST',
    GET_TRIAL_BALANCE_RESPONSE: 'GET_TRIAL_BALANCE_RESPONSE',
    RESET_LOADER:'TB_RESET_LOADER',
    GET_FLAT_ACCOUNT_W_GROUP_REQUEST: 'GET_FLAT_ACCOUNT_W_GROUP_REQUEST',
    GET_FLAT_ACCOUNT_W_GROUP_RESPONSE: 'GET_FLAT_ACCOUNT_W_GROUP_RESPONSE',

    GET_ACC_TRANSACTION: 'GET_ACC_TRANSACTION',
    GET_ACC_TRANSACTION_RESPONSE: 'GET_ACC_TRANSACTION_RESPONSE',
    GET_LEDGER_ACCOUNT: 'GET_LEDGER_ACCOUNT',
    GET_LEDGER_ACCOUNT_RESPONSE: 'GET_LEDGER_ACCOUNT_RESPONSE',

    GET_MORE_ACC_TRANSACTION: 'GET_MORE_ACC_TRANSACTION',
    GET_MORE_ACC_TRANSACTION_RESPONSE: 'GET_MORE_ACC_TRANSACTION_RESPONSE',
};
