export const ReportConst = {
    PROFIT_LOSS_CHART: {
        GET_INCOME_DATA_REQUEST: 'GET_INCOME_DATA_REQUEST',
        GET_INCOME_DATA_RESPONSE: 'GET_INCOME_DATA_RESPONSE',
        GET_INCOME_DATA_ERROR: 'GET_INCOME_DATA_ERROR',

        GET_EXPENSES_DATA_REQUEST: 'GET_EXPENSES_DATA_REQUEST',
        GET_EXPENSES_DATA_RESPONSE: 'GET_EXPENSES_DATA_RESPONSE',
        GET_EXPENSES_DATA_ERROR: 'GET_EXPENSES_DATA_ERROR'
    },
    PROFIT_LOSS_SHEET: {
        GET_PROFIT_LOSS_SHEET_REQUEST: 'GET_PROFIT_LOSS_SHEET_REQUEST',
        GET_PROFIT_LOSS_SHEET_RESPONSE: 'GET_PROFIT_LOSS_SHEET_RESPONSE'
    },
    BALANCE_SHEET: {
        GET_BALANCE_SHEET_REQUEST: 'GET_BALANCE_SHEET_REQUEST',
        GET_BALANCE_SHEET_RESPONSE: 'GET_BALANCE_SHEET_RESPONSE'
    },
    SET_REPORT_FILTER_TYPE: 'SET_REPORT_FILTER_TYPE'
};
