export const LoginConstants = {
  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_RESPONSE: 'SIGNUP_RESPONSE',
  LOGIN_WITH_PASSWORD_REQUEST: 'LOGIN_WITH_PASSWORD_REQUEST',
  LOGIN_WITH_PASSWORD_RESPONSE: 'LOGIN_WITH_PASSWORD_RESPONSE',

  SIGNUP_WITH_MOBILE_REQUEST: 'SIGNUP_WITH_MOBILE_REQUEST',
  SIGNUP_WITH_MOBILE_RESPONCE: 'SIGNUP_WITH_MOBILE_RESPONCE',
  VERIFY_MOBILE_REQUEST: 'VERIFY_MOBILE_REQUEST',
  VERIFY_MOBILE_RESPONCE: 'VERIFY_MOBILE_RESPONCE',

  VERIFY_TWOWAYAUTH_REQUEST: 'VERIFY_TWOWAYAUTH_REQUEST',
  VERIFY_TWOWAYAUTH_RESPONSE: 'VERIFY_TWOWAYAUTH_RESPONSE',

  SIGNUP_WITH_EMAIL_REQUEST: 'SIGNUP_WITH_EMAIL_REQUEST',
  SIGNUP_WITH_EMAIL_RESPONCE: 'SIGNUP_WITH_EMAIL_RESPONCE',
  VERIFY_EMAIL_REQUEST: 'VERIFY_EMAIL_REQUEST',
  VERIFY_EMAIL_RESPONCE: 'VERIFY_EMAIL_RESPONCE',

  SET_INITIAL_SESSION_STATE: 'SET_INITIAL_SESSION_STATE',
  LOGOUT: 'LOGOUT',
  RESET_LOGIN_STATE: 'RESET_LOGIN_STATE'
}
