export const LoginConstants = {
  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_RESPONSE: 'SIGNUP_RESPONSE',
  LOGIN_WITH_PASSWORD_REQUEST: 'LOGIN_WITH_PASSWORD_REQUEST',
  LOGIN_WITH_PASSWORD_RESPONSE: 'LOGIN_WITH_PASSWORD_RESPONSE',
  LOGOUT: 'LOGOUT',
  RESET_LOGIN_STATE: 'RESET_LOGIN_STATE'
}
