export const ReportConst = {
  PROFIT_LOSS_CHART: {
    GET_PROFIT_LOSS_CHART_DATA_ACTIVE_YEAR: 'GET_PROFIT_LOSS_CHART_DATA_ACTIVE_YEAR',
    GET_PROFIT_LOSS_CHART_DATA_ACTIVE_YEAR_RESPONSE: 'GET_PROFIT_LOSS_CHART_DATA_ACTIVE_YEAR_RESPONSE',
    GET_PROFIT_LOSS_CHART_DATA_ACTIVE_YEAR_ERROR_RESPONSE: 'GET_PROFIT_LOSS_CHART_DATA_ACTIVE_YEAR_ERROR_RESPONSE',
    GET_PROFIT_LOSS_CHART_DATA_LAST_YEAR: 'GET_PROFIT_LOSS_CHART_DATA_LAST_YEAR',
    GET_PROFIT_LOSS_CHART_DATA_LAST_YEAR_RESPONSE: 'GET_PROFIT_LOSS_CHART_DATA_LAST_YEAR_RESPONSE'
  },
  SET_PROFIT_LOSS_CHART_FILTER_TYPE: 'SET_PROFIT_LOSS_CHART_FILTER_TYPE'
};
