export const DashboardConst = {
    EXPENSES_CHART: {
        GET_EXPENSES_CHART_DATA_ACTIVE_YEAR: 'GET_EXPENSES_CHART_DATA_ACTIVE_YEAR',
        GET_EXPENSES_CHART_DATA_ACTIVE_YEAR_RESPONSE: 'GET_EXPENSES_CHART_DATA_ACTIVE_YEAR_RESPONSE',
        GET_EXPENSES_CHART_DATA_ACTIVE_YEAR_ERROR: 'GET_EXPENSES_CHART_DATA_ACTIVE_YEAR_ERROR',
        GET_EXPENSES_CHART_DATA_LAST_YEAR: 'GET_EXPENSES_CHART_DATA_LAST_YEAR',
        GET_EXPENSES_CHART_DATA_LAST_YEAR_RESPONSE: 'GET_EXPENSES_CHART_DATA_LAST_YEAR_RESPONSE',
        GET_EXPENSES_CHART_DATA_LAST_YEAR_ERROR: 'GET_EXPENSES_CHART_DATA_LAST_YEAR_ERROR'
    },
    REVENUE_CHART: {
        GET_REVENUE_CHART_DATA_ACTIVE_YEAR: 'GET_REVENUE_CHART_DATA_ACTIVE_YEAR',
        GET_REVENUE_CHART_DATA_ACTIVE_YEAR_RESPONSE: 'GET_REVENUE_CHART_DATA_ACTIVE_YEAR_RESPONSE',
        GET_REVENUE_CHART_DATA_ACTIVE_YEAR_ERROR: 'GET_REVENUE_CHART_DATA_ACTIVE_YEAR_ERROR',
        GET_REVENUE_CHART_DATA_LAST_YEAR: 'GET_REVENUE_CHART_DATA_LAST_YEAR',
        GET_REVENUE_CHART_DATA_LAST_YEAR_RESPONSE: 'GET_REVENUE_CHART_DATA_LAST_YEAR_RESPONSE',
        GET_REVENUE_CHART_DATA_LAST_YEAR_ERROR: 'GET_REVENUE_CHART_DATA_LAST_YEAR_ERROR',
    },
    SET_CHART_FILTER_TYPE: 'SET_CHART_FILTER_TYPE',
    RESET_DASHBOARD_STATE: 'RESET_DASHBOARD_STATE'
};
