export const DashboardConst = {
    EXPENSES_CHART: {
        GET_EXPENSES_CHART_DATA: 'GET_EXPENSES_CHART_DATA',
        GET_EXPENSES_CHART_DATA_RESPONSE: 'GET_EXPENSES_CHART_DATA_RESPONSE',
        GET_EXPENSES_CHART_DATA_ERROR_RESPONSE: 'GET_EXPENSES_CHART_DATA_ERROR_RESPONSE',
    },
    REVENUE_CHART: {
        GET_REVENUE_CHART_DATA: 'GET_REVENUE_CHART_DATA',
        GET_REVENUE_CHART_DATA_RESPONSE: 'GET_REVENUE_CHART_DATA_RESPONSE',
        GET_REVENUE_CHART_DATA_ERROR_RESPONSE: 'GET_REVENUE_CHART_DATA_ERROR_RESPONSE',
    },
    SET_CHART_FILTER_TYPE: 'SET_CHART_FILTER_TYPE',
    RESET_DASHBOARD_STATE: 'RESET_DASHBOARD_STATE'
};
